ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Drop user if exists (ignore error if not exists)
BEGIN
   EXECUTE IMMEDIATE 'DROP USER r2sample CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE USER r2sample IDENTIFIED BY r2sample;
GRANT CONNECT, RESOURCE, DBA TO r2sample;
GRANT CREATE SESSION TO r2sample;
GRANT UNLIMITED TABLESPACE TO r2sample;

COMMIT;
EXIT;
